# Extended knowledge for smarter Josiah: extra Q&A pairs merged into the main knowledge engine.
# Format: (list of keyword phrases, list of reply strings)

EXTRA_KNOWLEDGE_AI = [
    (["how do i study better", "study better", "best way to study"], ["Try the Pomodoro Technique: 25 minutes of focus, then a 5-minute break. Use active recall—test yourself instead of just re-reading. Spaced repetition (review after 1 day, 3 days, a week) really works."]),
    (["how to memorize", "memorize better", "remember things"], ["Active recall helps: close the book and try to recall. Use mnemonics (silly sentences or acronyms). Connect new info to what you already know. Sleep and spaced repetition strengthen memory."]),
    (["how to focus", "stay focused", "concentration"], ["Remove distractions (phone away). Use the Pomodoro Technique. Study in a quiet place at the same time daily. Short breaks help more than long cramming."]),
    (["exam tips", "test tips", "how to do well on exam"], ["Read all questions first and budget time. Do easier questions first. Show your work in math. Review answers if you have time. Get good sleep the night before."]),
    (["what is pomodoro", "pomodoro technique"], ["The Pomodoro Technique: work for 25 minutes, then take a 5-minute break. After four cycles, take a longer break (15–30 min). It helps focus and prevents burnout."]),
    (["how to take notes", "note taking", "good notes"], ["Capture main ideas and key details, not every word. Use headings, bullets, and abbreviations. Review and tidy notes soon after class. Summarize in your own words."]),
    (["how to write an essay", "essay writing", "write essay"], ["Start with a clear thesis. Each body paragraph = one main idea + evidence. Use transition words. Introduction hooks and states thesis; conclusion restates it and summarizes."]),
    (["what is a thesis", "thesis statement"], ["A thesis statement is one or two sentences that state the main idea of your essay. It should be specific and arguable. It usually goes at the end of your introduction."]),
    (["difference between its and its", "its vs its", "when to use its"], ["Its (no apostrophe) = possessive: 'The dog wagged its tail.' It's (with apostrophe) = it is or it has: 'It's raining.' If you can say 'it is,' use it's."]),
    (["their there theyre", "their vs there", "they're"], ["Their = belonging to them. There = a place or 'there is.' They're = they are. Example: They're going over there to get their books."]),
    (["your youre", "your vs you're"], ["Your = belonging to you. You're = you are. 'You're going to love your new bike.'"]),
    (["what is 15 percent of 80", "15% of 80"], ["15% of 80 = 0.15 × 80 = 12. So the answer is 12."]),
    (["what is 20 percent of 50", "20% of 50"], ["20% of 50 = 0.20 × 50 = 10. So the answer is 10."]),
    (["solve 2x plus 5 equals 15", "2x + 5 = 15"], ["Subtract 5: 2x = 10. Divide by 2: x = 5. So x = 5."]),
    (["solve 3x equals 12", "3x = 12"], ["Divide both sides by 3: x = 12/3 = 4. So x = 4."]),
    (["quadratic formula", "solve quadratic"], ["For ax² + bx + c = 0, use x = (-b ± √(b²-4ac)) / (2a). The part b²-4ac is the discriminant. If it's positive, two real solutions; zero, one; negative, no real solutions."]),
    (["pythagorean theorem", "pythagoras"], ["In a right triangle, a² + b² = c² where c is the hypotenuse. Use it to find any side when you know the other two."]),
    (["area of circle", "circle area"], ["Area = πr². So for radius 5, area = π × 25 ≈ 78.54 square units."]),
    (["circumference of circle", "circle circumference"], ["Circumference = 2πr. For radius 5, that's 2 × π × 5 ≈ 31.42."]),
    (["volume of sphere", "sphere volume"], ["Volume = (4/3)πr³. For radius 3, volume ≈ 113.1 cubic units."]),
    (["newton first law", "first law of motion"], ["Newton's first law: an object stays at rest or in constant motion unless a force acts on it. That's inertia."]),
    (["newton second law", "f equals ma"], ["Newton's second law: F = ma. Force equals mass times acceleration. Bigger force or smaller mass means more acceleration."]),
    (["newton third law", "action reaction"], ["Newton's third law: for every action there is an equal and opposite reaction. When you push a wall, the wall pushes back."]),
    (["how does gravity work", "what is gravity"], ["Gravity is the force that pulls objects with mass toward each other. On Earth it gives things weight. Einstein described it as curvature of space-time."]),
    (["how does photosynthesis work", "photosynthesis"], ["Plants use sunlight, water, and CO₂ to make glucose and oxygen. It happens in chloroplasts using chlorophyll. The light reactions capture light; the Calvin cycle builds sugar."]),
    (["water cycle", "how does the water cycle work"], ["Water evaporates, condenses into clouds, falls as rain or snow (precipitation), and runs off or soaks in. Then it evaporates again. The cycle repeats."]),
    (["how do airplanes fly", "why do planes fly"], ["Wings are shaped so air moves faster over the top than the bottom, creating lower pressure above and lift. Engines provide thrust. Lift, thrust, weight, and drag all play a part."]),
    (["why is the sky blue", "blue sky"], ["Sunlight is scattered by the atmosphere. Shorter (blue) wavelengths scatter more than longer (red) ones, so we see blue when we look away from the Sun."]),
    (["why do we dream", "what are dreams"], ["Dreams mostly happen during REM sleep. Theories include processing emotions and memories, problem-solving, or the brain making sense of random signals. We still don't know for sure."]),
    (["how do vaccines work", "vaccines"], ["Vaccines train the immune system by showing it a harmless version of a germ (or part of it). The body makes antibodies and remembers the germ, so it can fight the real thing later."]),
    (["what is dna", "dna"], ["DNA carries genetic information. It's a double helix of two strands. The sequence of bases (A, T, G, C) codes for proteins and traits. We inherit it from our parents."]),
    (["what is evolution", "evolution"], ["Evolution is the change in species over time. Natural selection means organisms better suited to the environment tend to survive and reproduce more. Over many generations, species change."]),
    (["what is climate change", "climate change"], ["Climate change is long-term change in global temperatures and weather. Extra greenhouse gases (like CO₂) from human activity trap more heat. Result: warming, melting ice, and more extreme weather."]),
    (["how do magnets work", "magnets"], ["Magnets have north and south poles. Like poles repel; opposite attract. Magnetic fields come from moving charges. Materials like iron can become magnetized when the tiny magnetic domains align."]),
    (["what is electricity", "how does electricity work"], ["Electricity is the flow of electric charge (usually electrons). Current (amperes) is the rate of flow; voltage (volts) is the push; resistance (ohms) opposes flow. V = IR."]),
    (["what is an atom", "atoms"], ["An atom is the smallest unit of an element. It has a nucleus (protons and neutrons) and electrons around it. The number of protons defines the element."]),
    (["what is a molecule", "molecules"], ["A molecule is two or more atoms bonded together. Water is H₂O—two hydrogen, one oxygen. Molecules can be simple or very large like DNA."]),
    (["periodic table", "elements"], ["The periodic table arranges elements by atomic number and properties. Rows are periods; columns are groups. Elements in the same group often behave similarly."]),
    (["acid and base", "ph"], ["Acids donate protons (H⁺); bases accept them. pH measures acidity: below 7 is acid, 7 is neutral, above 7 is base. Vinegar is acidic; baking soda solution is basic."]),
    (["chemical reaction", "what is a chemical reaction"], ["A chemical reaction is when substances change into new substances. Bonds break and form. Signs: colour change, gas, heat, or precipitate. Mass is conserved."]),
    (["what is a cell", "cells"], ["Cells are the basic units of life. They have a membrane, cytoplasm, and DNA. Plant cells have a cell wall and chloroplasts; animal cells don't."]),
    (["what is the solar system", "solar system"], ["The solar system has the Sun and everything that orbits it: eight planets, dwarf planets, moons, asteroids, comets. The Sun has almost all the mass."]),
    (["what is a black hole", "black holes"], ["A black hole is a region where gravity is so strong nothing, not even light, can escape. They form when massive stars collapse. The boundary is the event horizon."]),
    (["speed of light", "how fast is light"], ["Light travels at about 300,000 km/s (186,000 miles per second) in a vacuum. Nothing with mass can reach that speed."]),
    (["how old is the earth", "age of earth"], ["Earth is about 4.5 billion years old. Scientists use radiometric dating of rocks and meteorites to determine this."]),
    (["how old is the universe", "age of universe"], ["The universe is about 13.8 billion years old, based on the expansion rate and the cosmic microwave background."]),
    (["why do we have seasons", "seasons"], ["Earth's axis is tilted. As we orbit the Sun, different parts get more direct sunlight. When your hemisphere is tilted toward the Sun, it's summer; away, winter."]),
    (["why do we have day and night", "day and night"], ["Earth rotates once about every 24 hours. The side facing the Sun has day; the side away has night."]),
    (["what causes thunder", "thunder and lightning"], ["Lightning heats the air so fast it creates a shock wave—that's thunder. Light travels faster than sound, so we see lightning before we hear thunder."]),
    (["what is a rainbow", "rainbows"], ["Rainbows form when sunlight is refracted and reflected inside water droplets. We see a band of colours: red, orange, yellow, green, blue, indigo, violet."]),
    (["capital of canada"], ["The capital of Canada is Ottawa. It's in Ontario. Toronto is the largest city but Ottawa is the capital."]),
    (["capital of australia"], ["The capital of Australia is Canberra. It was chosen as a compromise between Sydney and Melbourne."]),
    (["capital of india"], ["The capital of India is New Delhi. It's part of the National Capital Territory. Mumbai is the largest city."]),
    (["capital of china"], ["The capital of China is Beijing. It's a major political and cultural centre. Shanghai is the largest city."]),
    (["capital of japan"], ["The capital of Japan is Tokyo. It's one of the world's largest cities and the seat of the emperor and government."]),
    (["capital of brazil"], ["The capital of Brazil is Brasília. It was built as a planned capital in the 1960s. São Paulo is the largest city."]),
    (["capital of germany"], ["The capital of Germany is Berlin. It became the capital again after reunification in 1990."]),
    (["capital of france"], ["The capital of France is Paris. It's a global centre for culture, fashion, and art."]),
    (["capital of italy"], ["The capital of Italy is Rome. It was the heart of the Roman Empire and is home to the Vatican."]),
    (["capital of spain"], ["The capital of Spain is Madrid. It's in the centre of the country and is the largest city."]),
    (["capital of uk", "capital of united kingdom"], ["The capital of the United Kingdom is London. It's in England and is one of the world's major cities."]),
    (["capital of usa", "capital of america", "capital of united states"], ["The capital of the United States is Washington, D.C. It's a federal district, not a state. New York is the largest city."]),
    (["largest country", "biggest country"], ["Russia is the largest country by area. It spans Europe and Asia. Canada is second, then the USA and China."]),
    (["smallest country"], ["Vatican City is the smallest country by area and population. It's about 44 hectares with around 800 residents."]),
    (["longest river"], ["The Nile in Africa is often cited as the longest river (about 6,650 km). The Amazon is close and has the largest flow."]),
    (["tallest mountain", "highest mountain"], ["Mount Everest is the highest peak above sea level at 8,849 m. It's in the Himalayas on the border of Nepal and China."]),
    (["largest desert"], ["Antarctica is the largest desert (cold desert). The largest hot desert is the Sahara in North Africa."]),
    (["deepest ocean", "mariana trench"], ["The Mariana Trench in the Pacific is the deepest point—about 11 km down. The Challenger Deep is the lowest spot."]),
    (["how many bones", "bones in body", "human skeleton"], ["Adults have 206 bones. They support the body, protect organs, and work with muscles for movement."]),
    (["how many muscles", "muscles in body"], ["Humans have over 600 muscles. They allow movement, maintain posture, and help circulation and digestion."]),
    (["how does the heart work", "heart"], ["The heart has four chambers. It pumps blood: oxygen-poor blood goes to the lungs; oxygen-rich blood goes to the body. Valves keep flow one-way."]),
    (["how does the brain work", "brain"], ["The brain has billions of neurons that communicate via electrical and chemical signals. Different regions handle movement, sensation, thought, memory, and more."]),
    (["what is blood", "blood"], ["Blood carries oxygen, nutrients, and waste. Red blood cells carry oxygen; white cells fight infection; platelets help clotting. Plasma is the liquid part."]),
    (["what is digestion", "digestive system"], ["Digestion breaks down food so the body can absorb nutrients. It starts in the mouth, continues in the stomach and small intestine, and waste leaves through the large intestine."]),
    (["what is the immune system", "immune system"], ["The immune system defends against germs. White blood cells, antibodies, and other parts identify and attack invaders. Vaccines train it to recognise specific pathogens."]),
    (["what is a virus", "viruses"], ["Viruses are tiny infectious agents. They need a host cell to reproduce. They're not technically alive. Vaccines and immune responses help fight them."]),
    (["what is bacteria", "bacteria"], ["Bacteria are single-celled organisms. Some cause disease; many are harmless or helpful (e.g. in digestion). Antibiotics treat bacterial infections."]),
    (["what is a gene", "genes"], ["Genes are segments of DNA that code for proteins or affect traits. We inherit them from our parents. They influence how we look and how our bodies work."]),
    (["what is mitosis", "mitosis"], ["Mitosis is when a cell divides to make two identical daughter cells. It's used for growth and repair. The chromosomes are copied and split."]),
    (["what is meiosis", "meiosis"], ["Meiosis produces gametes (egg and sperm). It has two divisions and results in four cells with half the chromosomes. That's why offspring get half from each parent."]),
    (["what is an ecosystem", "ecosystem"], ["An ecosystem includes all living things and their physical environment in an area. Energy flows (e.g. sun → plants → animals); nutrients cycle."]),
    (["what is a food chain", "food chain"], ["A food chain shows who eats whom: producer (plant) → herbivore → carnivore. Food webs show many interconnected chains."]),
    (["what is renewable energy", "renewable"], ["Renewable energy comes from sources that don't run out or replenish: solar, wind, hydro, geothermal, biomass. They produce less carbon than fossil fuels."]),
    (["what is global warming", "global warming"], ["Global warming is the long-term rise in Earth's average temperature, mainly from more greenhouse gases (e.g. CO₂) from burning fossil fuels and other human activity."]),
    (["what is recycling", "recycling"], ["Recycling turns used materials into new products. It reduces waste and can save energy and resources. Paper, plastic, glass, and metal are commonly recycled."]),
    (["what is plastic", "plastic"], ["Plastic is a material made from polymers—long chains of molecules. It's durable and versatile but many types don't break down easily, causing pollution."]),
    (["what is the internet", "internet"], ["The internet is a global network of networks. Computers and devices connect and share data using standard protocols. It supports the web, email, and much more."]),
    (["what is ai", "artificial intelligence"], ["Artificial intelligence (AI) is when machines perform tasks that usually need human intelligence—learning, reasoning, recognising patterns. Chatbots, recommendations, and self-driving cars use AI."]),
    (["what is coding", "programming", "code"], ["Coding (programming) is writing instructions for a computer in a programming language. Programs tell the computer what to do step by step."]),
    (["what is a robot", "robots"], ["A robot is a machine that can carry out actions automatically, often programmed or controlled by a computer. They're used in manufacturing, surgery, and exploration."]),
    (["what is a computer", "computers"], ["A computer is a machine that processes data using programs. It has hardware (CPU, memory, storage) and software. It can calculate, store data, and run applications."]),
    (["who invented the light bulb", "light bulb"], ["Thomas Edison is often credited with inventing a practical electric light bulb in the 1870s–80s. Others also contributed; it was improved over time."]),
    (["who invented the telephone", "telephone"], ["Alexander Graham Bell is credited with inventing the telephone in 1876. Others were working on similar ideas at the time."]),
    (["who discovered america", "america discovered"], ["Indigenous peoples had been in the Americas for thousands of years. From a European perspective, Columbus reached the Americas in 1492 (though he didn't land on mainland North America first)."]),
    (["who was einstein", "einstein"], ["Albert Einstein was a physicist who developed the theory of relativity and contributed to quantum theory. E = mc² is one of his famous equations. He won the Nobel Prize."]),
    (["who was newton", "isaac newton"], ["Isaac Newton was a scientist and mathematician. He described gravity and the laws of motion, and developed calculus. He's one of the most influential scientists in history."]),
    (["who was galileo", "galileo"], ["Galileo was an astronomer and physicist. He used a telescope to observe the Moon and Jupiter's moons, and supported the idea that Earth orbits the Sun."]),
    (["who was darwin", "charles darwin"], ["Charles Darwin proposed the theory of evolution by natural selection. His book 'On the Origin of Species' explained how species change over time."]),
    (["roman empire", "rome"], ["The Roman Empire was one of the largest ancient empires. It started in Rome and at its height covered much of Europe, North Africa, and the Middle East. It fell in the west in the 5th century."]),
    (["ancient egypt", "egyptians"], ["Ancient Egypt was a civilisation along the Nile. It had pharaohs, pyramids, hieroglyphics, and advances in writing, building, and medicine. It lasted thousands of years."]),
    (["world war 1", "first world war", "ww1"], ["World War I (1914–1918) involved many nations. It was triggered by alliances and the assassination of Archduke Franz Ferdinand. Trench warfare and new weapons made it very deadly."]),
    (["world war 2", "second world war", "ww2"], ["World War II (1939–1945) was a global conflict. Major powers included the Allies (e.g. USA, UK, USSR) and the Axis (Germany, Japan, Italy). It ended with the use of atomic bombs and the defeat of the Axis."]),
    (["moon landing", "apollo 11"], ["Humans first landed on the Moon on July 20, 1969 (Apollo 11). Neil Armstrong and Buzz Aldrin walked on the surface; Michael Collins orbited above."]),
    (["fun fact", "random fact", "interesting fact"], ["Here's one: honey never spoils—archaeologists have found edible honey in ancient tombs. Or: octopuses have three hearts and blue blood. Want more? Ask about a topic!"]),
    (["tell me a joke", "joke", "funny"], ["Why did the scarecrow win an award? He was outstanding in his field! Or: What do you call a bear with no teeth? A gummy bear. I'm Josiah—ask me for more or switch to facts!"]),
    (["how are you", "how do you do"], ["I'm doing great, thanks! I'm Josiah and I'm here to help. What would you like to know?"]),
    (["what is your name", "who are you"], ["I'm Josiah! I'm a chatbot with a big knowledge base. I can help with science, math, writing, study tips, and lots more. What can I do for you?"]),
    (["can you help", "help me with"], ["Of course! I'm Josiah. Just ask your question—math, science, writing, study tips, or general knowledge. I'll do my best to answer."]),
    (["i dont understand", "confused", "explain again"], ["No problem! Tell me which part you'd like me to explain again, or ask the same question in different words. I'm Josiah and I'm here to help."]),
    (["that was helpful", "thanks that helped"], ["Glad it helped! If you have more questions, just ask. I'm Josiah."]),
    (["goodbye", "bye", "see you"], ["Goodbye! Come back anytime you have questions. I'm Josiah."]),
    # More geography and places
    (["capital of morocco"], ["The capital of Morocco is Rabat. Casablanca is the largest city."]),
    (["capital of algeria"], ["The capital of Algeria is Algiers. It's on the Mediterranean coast."]),
    (["capital of tunisia"], ["The capital of Tunisia is Tunis. It's in the north of the country."]),
    (["capital of libya"], ["The capital of Libya is Tripoli. It's the largest city and main port."]),
    (["capital of sudan"], ["The capital of Sudan is Khartoum. The Blue and White Nile meet there."]),
    (["capital of ethiopia"], ["The capital of Ethiopia is Addis Ababa. It's one of the highest capitals in Africa."]),
    (["capital of tanzania"], ["The capital of Tanzania is Dodoma. Dar es Salaam is the largest city."]),
    (["capital of uganda"], ["The capital of Uganda is Kampala. It's near Lake Victoria."]),
    (["capital of ghana"], ["The capital of Ghana is Accra. It's on the Atlantic coast."]),
    (["capital of senegal"], ["The capital of Senegal is Dakar. It's the westernmost city in mainland Africa."]),
    (["capital of ivory coast", "capital of cote divoire"], ["The capital of Ivory Coast is Yamoussoukro. Abidjan is the largest city and economic centre."]),
    (["capital of cameroon"], ["The capital of Cameroon is Yaoundé. Douala is the largest city."]),
    (["capital of zimbabwe"], ["The capital of Zimbabwe is Harare. It's the largest city."]),
    (["capital of zambia"], ["The capital of Zambia is Lusaka. It's the largest city."]),
    (["capital of angola"], ["The capital of Angola is Luanda. It's on the Atlantic coast."]),
    (["capital of mozambique"], ["The capital of Mozambique is Maputo. It's in the south."]),
    (["capital of madagascar"], ["The capital of Madagascar is Antananarivo. It's in the central highlands."]),
    (["capital of botswana"], ["The capital of Botswana is Gaborone. It's near the border with South Africa."]),
    (["capital of namibia"], ["The capital of Namibia is Windhoek. It's in the centre of the country."]),
    (["capital of rwanda"], ["The capital of Rwanda is Kigali. It's the largest city."]),
    (["capital of cuba"], ["The capital of Cuba is Havana. It's known for its colonial architecture and culture."]),
    (["capital of jamaica"], ["The capital of Jamaica is Kingston. It's the largest city and main port."]),
    (["capital of haiti"], ["The capital of Haiti is Port-au-Prince. It's on the Gulf of Gonâve."]),
    (["capital of dominican republic"], ["The capital of the Dominican Republic is Santo Domingo. It's the oldest European city in the Americas."]),
    (["capital of puerto rico"], ["The capital of Puerto Rico is San Juan. It's a U.S. territory."]),
    (["capital of colombia"], ["The capital of Colombia is Bogotá. It's high in the Andes."]),
    (["capital of venezuela"], ["The capital of Venezuela is Caracas. It's in the north."]),
    (["capital of peru"], ["The capital of Peru is Lima. It's on the Pacific coast."]),
    (["capital of chile"], ["The capital of Chile is Santiago. It's in the centre of the long, narrow country."]),
    (["capital of ecuador"], ["The capital of Ecuador is Quito. It's one of the highest capitals in the world."]),
    (["capital of bolivia"], ["Bolivia has two capitals: Sucre (constitutional) and La Paz (government seat)."]),
    (["capital of paraguay"], ["The capital of Paraguay is Asunción. It's one of the oldest cities in South America."]),
    (["capital of uruguay"], ["The capital of Uruguay is Montevideo. It's on the Río de la Plata."]),
    (["capital of costa rica"], ["The capital of Costa Rica is San José. It's in the central valley."]),
    (["capital of panama"], ["The capital of Panama is Panama City. It's near the Panama Canal."]),
    (["capital of nicaragua"], ["The capital of Nicaragua is Managua. It's the largest city."]),
    (["capital of honduras"], ["The capital of Honduras is Tegucigalpa. It's in the central highlands."]),
    (["capital of el salvador"], ["The capital of El Salvador is San Salvador. It's the largest city."]),
    (["capital of guatemala"], ["The capital of Guatemala is Guatemala City. It's the largest city in Central America."]),
    (["capital of belize"], ["The capital of Belize is Belmopan. Belize City is the largest city."]),
    # More science
    (["what is force", "force physics"], ["In physics, force is a push or pull that can change an object's motion. F = ma links force to mass and acceleration. It's measured in newtons."]),
    (["what is pressure", "pressure"], ["Pressure is force per unit area. It's measured in pascals (or psi, bar). Air pressure, water pressure, and blood pressure are common examples."]),
    (["what is density", "density"], ["Density is mass per unit volume (e.g. kg/m³ or g/cm³). Dense objects are heavy for their size. Water has density 1 g/cm³; things float if less dense than the fluid."]),
    (["what is temperature", "temperature"], ["Temperature measures how hot or cold something is. Common scales: Celsius, Fahrenheit, Kelvin. It's related to the average kinetic energy of particles."]),
    (["what is heat", "heat"], ["Heat is energy transferred because of a temperature difference. It flows from hotter to colder. It can change temperature or cause phase changes (e.g. melting)."]),
    (["what is radiation", "radiation"], ["Radiation is energy or particles moving through space. Light, heat, radio waves, and X-rays are forms. Nuclear radiation comes from unstable atoms."]),
    (["what is a chemical bond", "chemical bond"], ["A chemical bond holds atoms together in molecules. Types include covalent (sharing electrons), ionic (transfer of electrons), and metallic. Bonds store and release energy."]),
    (["what is oxidation", "oxidation"], ["Oxidation is loss of electrons (or gain of oxygen). Rust is iron oxidizing. The opposite is reduction. Together they're redox reactions."]),
    (["what is a catalyst", "catalyst"], ["A catalyst speeds up a reaction without being used up. Enzymes are biological catalysts. They lower the energy needed for the reaction."]),
    (["what is an enzyme", "enzymes"], ["Enzymes are proteins that catalyse biological reactions. They're specific to their substrate. They help digestion, DNA copying, and many other processes."]),
    (["what is photosynthesis formula", "equation for photosynthesis"], ["The overall equation is: 6 CO₂ + 6 H₂O + light → C₆H₁₂O₆ (glucose) + 6 O₂. Plants take in carbon dioxide and water, use light, and produce glucose and oxygen."]),
    (["what is cellular respiration", "cellular respiration"], ["Cellular respiration breaks down glucose to release energy: C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + ATP. It happens in mitochondria. ATP is the energy currency."]),
    (["what is mitosis vs meiosis"], ["Mitosis produces two identical cells for growth and repair. Meiosis produces four cells with half the chromosomes for reproduction (egg and sperm)."]),
    (["what is a chromosome", "chromosomes"], ["Chromosomes are packaged DNA. Humans have 46 (23 pairs) in most cells. They carry genes. Sex chromosomes (X and Y) determine biological sex."]),
    (["what is mutation", "mutations"], ["A mutation is a change in DNA. It can be harmless, harmful, or beneficial. Mutations can cause disease or drive evolution when they affect offspring."]),
    (["what is natural selection simple"], ["Natural selection means organisms with traits that help survival and reproduction tend to have more offspring. Over time, those traits become more common. That's how species change."]),
    (["what is an ecosystem simple"], ["An ecosystem is all the living things and their environment in an area. Energy flows (e.g. sun → plants → animals); nutrients cycle. Everything is connected."]),
    (["what is biodiversity simple"], ["Biodiversity is the variety of life—different species, genes, and ecosystems. It keeps ecosystems healthy and provides food, medicine, and other benefits."]),
    (["what is pollution", "pollution"], ["Pollution is harmful substances or energy in the environment. Air, water, and soil can be polluted. It harms health and ecosystems. Reducing waste and emissions helps."]),
    (["what is recycling simple"], ["Recycling turns used materials into new products. It reduces waste and saves resources. Paper, plastic, glass, and metal can often be recycled."]),
    (["what is solar energy", "solar power"], ["Solar energy is energy from the Sun. Solar panels convert it to electricity (photovoltaics) or use it for heat. It's renewable and clean."]),
    (["what is wind energy", "wind power"], ["Wind energy uses the wind to turn turbines that generate electricity. It's renewable. Wind farms are built on land or offshore."]),
    (["what is fossil fuel", "fossil fuels"], ["Fossil fuels (coal, oil, gas) formed from ancient plants and animals. Burning them releases energy but also CO₂ and other pollutants. They're non-renewable."]),
    (["what is greenhouse gas", "greenhouse gases"], ["Greenhouse gases (CO₂, methane, etc.) trap heat in the atmosphere. Some is natural; extra from human activity (e.g. burning fossil fuels) increases warming."]),
    (["what is the water cycle simple"], ["Water evaporates from oceans and land, forms clouds (condensation), falls as rain or snow (precipitation), and flows back. The cycle repeats."]),
    (["what is the rock cycle", "rock cycle"], ["Rocks can be igneous (from magma), sedimentary (from sediment), or metamorphic (changed by heat and pressure). They can change from one type to another over time."]),
    (["what is erosion", "erosion"], ["Erosion is when wind, water, or ice move soil and rock. It shapes landscapes (canyons, valleys). It can be sped up by deforestation and poor land use."]),
    (["what is weathering", "weathering"], ["Weathering is the breaking down of rocks by weather, water, and chemicals. It can be physical (freeze-thaw) or chemical (e.g. acid rain). It works with erosion to shape land."]),
    (["what is a volcano simple"], ["A volcano is where molten rock (magma) reaches the surface. It can erupt with lava, ash, and gas. They form at plate boundaries or hot spots."]),
    (["what is an earthquake simple"], ["An earthquake is shaking of the ground from sudden release of energy, usually from movement along a fault. They're measured with seismometers; magnitude scales describe size."]),
    (["what is a tsunami", "tsunami"], ["A tsunami is a series of huge waves usually caused by an underwater earthquake, landslide, or volcanic eruption. They can travel across oceans and cause great damage on shore."]),
    (["what is a hurricane simple"], ["A hurricane is a huge storm with strong winds and heavy rain. It forms over warm ocean water. Other names: typhoon, cyclone. They can cause flooding and damage."]),
    (["what is climate", "climate vs weather"], ["Weather is short-term (today's rain, this week's heat). Climate is long-term patterns (e.g. a region's average temperature and rainfall over decades)."]),
    (["what is the atmosphere", "atmosphere"], ["The atmosphere is the layer of gases around Earth. It has nitrogen, oxygen, and other gases. It protects us, provides oxygen, and affects weather and climate."]),
    (["what is the ozone layer", "ozone"], ["The ozone layer is a region in the stratosphere with more ozone (O₃). It absorbs much of the Sun's UV radiation, protecting life. CFCs once damaged it; the hole is healing."]),
    (["what is the moon", "moon"], ["The Moon is Earth's only natural satellite. It orbits Earth in about 27 days. It causes tides and has phases (new, full, etc.) as we see different amounts of its lit side."]),
    (["what is a star", "stars"], ["A star is a ball of gas that shines from nuclear fusion in its core. The Sun is a star. Stars vary in size, colour, and lifespan."]),
    (["what is a galaxy simple"], ["A galaxy is a huge collection of stars, gas, and dust held by gravity. The Milky Way is our galaxy. There are billions of galaxies in the universe."]),
    (["what is a nebula", "nebula"], ["A nebula is a cloud of gas and dust in space. Some are where stars form; others are debris from dead stars. They can be very colourful in images."]),
    (["what is a supernova", "supernova"], ["A supernova is the explosion of a massive star at the end of its life. It's extremely bright and can outshine a galaxy. It spreads heavy elements into space."]),
    (["what is a light year", "light year"], ["A light year is the distance light travels in one year—about 9.5 trillion km. It's used for huge distances in space, not time."]),
    (["what is the milky way"], ["The Milky Way is our galaxy—a spiral of hundreds of billions of stars. The Sun is in one of its arms. From Earth we see it as a band across the sky."]),
    (["what is mars like", "mars planet"], ["Mars is cold and dry with a thin atmosphere. It has rust-coloured dust, polar ice caps, and ancient riverbeds. Rovers have found evidence of past water."]),
    (["what is jupiter like", "jupiter planet"], ["Jupiter is a gas giant—no solid surface. It has a Great Red Spot (storm), many moons (e.g. Europa, Ganymede), and strong magnetic field. It's the largest planet."]),
    (["what is saturn like", "saturn planet"], ["Saturn is a gas giant with spectacular rings of ice and rock. It has many moons; Titan has a thick atmosphere. It's the second largest planet."]),
    (["what is pluto", "pluto planet"], ["Pluto is a dwarf planet in the Kuiper Belt. It was reclassified in 2006. It's small, icy, and has moons. NASA's New Horizons visited it in 2015."]),
    (["what is an asteroid", "asteroids"], ["Asteroids are rocky objects that orbit the Sun, mostly between Mars and Jupiter. Some cross Earth's orbit. They're leftovers from the early solar system."]),
    (["what is a comet", "comets"], ["Comets are icy bodies that release gas and dust when near the Sun, forming a tail. Many come from the outer solar system. Halley's Comet returns every ~76 years."]),
    (["what is the space station", "iss"], ["The International Space Station (ISS) is a habitable satellite in low Earth orbit. Astronauts live there for months, doing science in microgravity. Several countries built it together."]),
    (["what is gravity simple"], ["Gravity is the force that pulls objects with mass together. On Earth it makes things fall and gives them weight. The Moon's gravity causes tides."]),
    (["what is friction simple"], ["Friction is a force that opposes motion between surfaces. It lets us walk and drive. Without it we'd slip. It comes from bumps and bonds between surfaces."]),
    (["what is energy", "energy physics"], ["Energy is the ability to do work or cause change. It can be kinetic (motion), potential (stored), heat, light, etc. It's conserved—it changes form but total stays the same."]),
    (["what is work physics"], ["In physics, work is force times distance (in the direction of the force). Lifting a box does work. No movement in the direction of the force means no work."]),
    (["what is power physics"], ["Power is the rate at which work is done or energy is transferred. It's measured in watts. A more powerful engine does the same work faster."]),
    (["what is velocity vs speed"], ["Speed is how fast (e.g. 50 km/h). Velocity is speed plus direction (e.g. 50 km/h north). Change in velocity (including direction) is acceleration."]),
    (["what is acceleration simple"], ["Acceleration is how quickly velocity changes—speeding up, slowing down, or changing direction. It's measured in m/s². F = ma links force to acceleration."]),
    (["what is momentum simple"], ["Momentum = mass × velocity. It's conserved: total momentum before a collision equals total after. Big or fast things have more momentum."]),
    (["what is kinetic energy simple"], ["Kinetic energy is the energy of motion. KE = (1/2)mv². Faster or heavier objects have more. It's one form of energy."]),
    (["what is potential energy simple"], ["Potential energy is stored energy. Gravitational PE = mgh (mass × g × height). A raised ball has PE that turns into kinetic energy when dropped."]),
    (["what is sound simple"], ["Sound is a wave of pressure through air (or another medium). It needs something to travel through—no sound in space. Pitch = frequency; loudness = amplitude."]),
    (["what is light simple"], ["Light is electromagnetic radiation we can see. It travels in waves and as particles (photons). It moves at about 300,000 km/s in a vacuum."]),
    (["what is reflection simple"], ["Reflection is when light (or sound) bounces off a surface. The angle of incidence equals the angle of reflection. Mirrors reflect light to form images."]),
    (["what is refraction simple"], ["Refraction is when light bends as it passes from one medium to another (e.g. air to water) because its speed changes. That's why a straw looks bent in water."]),
    (["what is electricity simple"], ["Electricity is the flow of electric charge (usually electrons). Current = flow rate; voltage = push; resistance = opposition. V = IR (Ohm's law)."]),
    (["what is a circuit", "electric circuit"], ["An electric circuit is a path for current. It needs a source (e.g. battery), conductors (wires), and often a load (e.g. bulb). Open circuit = no flow; closed = flow."]),
    (["what is a magnet simple"], ["A magnet has north and south poles. Like poles repel; opposite attract. It produces a magnetic field. Some materials (like iron) can be magnetized."]),
    (["what is electromagnet", "electromagnet"], ["An electromagnet is a magnet made by passing current through a coil of wire. Turn off the current and the magnetism stops. Used in motors, speakers, and cranes."]),
]
