# Extra smart knowledge: ~350 lines of Q&A for deeper coverage.
# Format: (list of keywords, list of reply strings)

EXTRA_SMART_KNOWLEDGE = [
    (["who invented the telephone", "alexander graham bell"], ["Alexander Graham Bell is credited with inventing the telephone in 1876. I'm Josiah."]),
    (["who invented the light bulb", "thomas edison"], ["Thomas Edison developed a practical incandescent light bulb. Others contributed to earlier versions. I'm Josiah."]),
    (["who invented the car", "first automobile"], ["Karl Benz built the first true automobile in 1885–1886. I'm Josiah."]),
    (["who invented the airplane", "wright brothers"], ["The Wright brothers, Orville and Wilbur, made the first controlled powered flight in 1903. I'm Josiah."]),
    (["who invented the computer", "first computer"], ["Early computers were built by many people; Charles Babbage designed early mechanical computers. I'm Josiah."]),
    (["who invented the internet", "origin of internet"], ["The internet grew from ARPANET and work by many researchers. No single person invented it. I'm Josiah."]),
    (["who invented printing", "gutenberg"], ["Johannes Gutenberg developed the printing press with movable type in the 15th century. I'm Josiah."]),
    (["who discovered penicillin"], ["Alexander Fleming discovered penicillin in 1928. It became the first widely used antibiotic. I'm Josiah."]),
    (["who discovered gravity", "newton gravity"], ["Isaac Newton described gravity; Einstein later refined our understanding with general relativity. I'm Josiah."]),
    (["who discovered america", "columbus"], ["Indigenous peoples were already in the Americas; Columbus reached them in 1492. I'm Josiah."]),
    (["capital of france", "france capital"], ["The capital of France is Paris. I'm Josiah."]),
    (["capital of germany", "germany capital"], ["The capital of Germany is Berlin. I'm Josiah."]),
    (["capital of italy", "italy capital"], ["The capital of Italy is Rome. I'm Josiah."]),
    (["capital of spain", "spain capital"], ["The capital of Spain is Madrid. I'm Josiah."]),
    (["capital of china", "china capital"], ["The capital of China is Beijing. I'm Josiah."]),
    (["capital of japan", "japan capital"], ["The capital of Japan is Tokyo. I'm Josiah."]),
    (["capital of india", "india capital"], ["The capital of India is New Delhi. I'm Josiah."]),
    (["capital of australia", "australia capital"], ["The capital of Australia is Canberra. I'm Josiah."]),
    (["capital of brazil", "brazil capital"], ["The capital of Brazil is Brasília. I'm Josiah."]),
    (["capital of canada", "canada capital"], ["The capital of Canada is Ottawa. I'm Josiah."]),
    (["capital of uk", "britain capital", "united kingdom capital"], ["The capital of the United Kingdom is London. I'm Josiah."]),
    (["capital of usa", "america capital", "united states capital"], ["The capital of the United States is Washington, D.C. I'm Josiah."]),
    (["capital of mexico", "mexico capital"], ["The capital of Mexico is Mexico City. I'm Josiah."]),
    (["capital of south korea", "korea capital"], ["The capital of South Korea is Seoul. I'm Josiah."]),
    (["capital of egypt", "egypt capital"], ["The capital of Egypt is Cairo. I'm Josiah."]),
    (["capital of nigeria", "nigeria capital"], ["The capital of Nigeria is Abuja. I'm Josiah."]),
    (["capital of kenya", "kenya capital"], ["The capital of Kenya is Nairobi. I'm Josiah."]),
    (["capital of argentina", "argentina capital"], ["The capital of Argentina is Buenos Aires. I'm Josiah."]),
    (["capital of south africa", "south africa capital"], ["South Africa has three capitals: Pretoria, Cape Town, and Bloemfontein. I'm Josiah."]),
    (["capital of russia", "russia capital"], ["The capital of Russia is Moscow. I'm Josiah."]),
    (["how many planets", "planets in solar system", "number of planets"], ["There are eight planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. I'm Josiah."]),
    (["how far is the sun", "distance to sun", "earth to sun distance"], ["Earth is about 150 million km (93 million miles) from the Sun on average. That distance is one astronomical unit. I'm Josiah."]),
    (["how far is the moon", "distance to moon"], ["The Moon is about 384,000 km (239,000 miles) from Earth on average. I'm Josiah."]),
    (["how old is the earth", "age of earth"], ["Earth is about 4.5 billion years old. I'm Josiah."]),
    (["how old is the universe", "age of universe"], ["The universe is about 13.8 billion years old. I'm Josiah."]),
    (["how many bones", "bones in human body"], ["Adults have about 206 bones. I'm Josiah."]),
    (["how many muscles", "muscles in human body"], ["There are over 600 muscles in the human body. I'm Josiah."]),
    (["how many teeth", "teeth in adults"], ["Adults typically have 32 teeth, including wisdom teeth. I'm Josiah."]),
    (["how many chromosomes", "human chromosomes"], ["Humans have 46 chromosomes (23 pairs). I'm Josiah."]),
    (["how many continents", "number of continents"], ["There are seven continents. I'm Josiah."]),
    (["how many countries", "number of countries"], ["There are about 195 countries in the world, depending on how you count. I'm Josiah."]),
    (["how many elements", "periodic table elements"], ["There are 118 known elements. I'm Josiah."]),
    (["how many moons does earth have"], ["Earth has one moon. I'm Josiah."]),
    (["how many moons does mars have"], ["Mars has two moons: Phobos and Deimos. I'm Josiah."]),
    (["how many moons does jupiter have"], ["Jupiter has over 80 known moons. I'm Josiah."]),
    (["what is the largest planet", "biggest planet"], ["Jupiter is the largest planet in our solar system. I'm Josiah."]),
    (["what is the smallest planet", "smallest planet"], ["Mercury is the smallest planet in our solar system. I'm Josiah."]),
    (["what is the hottest planet"], ["Venus is the hottest planet because its atmosphere traps heat. I'm Josiah."]),
    (["what is the coldest planet"], ["Uranus and Neptune are among the coldest. Neptune is very cold. I'm Josiah."]),
    (["what is the largest ocean"], ["The Pacific Ocean is the largest. I'm Josiah."]),
    (["what is the smallest country"], ["Vatican City is the smallest country by area. I'm Josiah."]),
    (["what is the longest river"], ["The Nile is often cited as the longest; the Amazon is also among the longest. I'm Josiah."]),
    (["what is the fastest animal", "fastest land animal"], ["The cheetah is the fastest land animal. The peregrine falcon is fastest in a dive. I'm Josiah."]),
    (["what is the largest animal", "biggest animal"], ["The blue whale is the largest animal ever known. I'm Josiah."]),
    (["what is the fastest fish"], ["The sailfish is among the fastest fish, reaching high speeds. I'm Josiah."]),
    (["what is the tallest animal"], ["The giraffe is the tallest living animal. I'm Josiah."]),
    (["what is the speed of light"], ["The speed of light is about 299,792 km per second in a vacuum. I'm Josiah."]),
    (["what is the speed of sound"], ["The speed of sound in air is about 343 m/s (varies with temperature). I'm Josiah."]),
    (["what is the boiling point of water"], ["Water boils at 100°C (212°F) at standard pressure. I'm Josiah."]),
    (["what is the freezing point of water"], ["Water freezes at 0°C (32°F). I'm Josiah."]),
    (["what is the normal body temperature", "human body temperature"], ["Normal human body temperature is about 37°C (98.6°F). I'm Josiah."]),
    (["what is the chemical formula of water"], ["Water is H2O—two hydrogen atoms and one oxygen. I'm Josiah."]),
    (["what is the chemical formula of salt"], ["Table salt is NaCl—sodium chloride. I'm Josiah."]),
    (["what is the chemical formula of sugar"], ["Table sugar (sucrose) is C12H22O11. I'm Josiah."]),
    (["what is dna", "what does dna stand for"], ["DNA (deoxyribonucleic acid) carries genetic instructions. It's a double helix. I'm Josiah."]),
    (["what is rna"], ["RNA (ribonucleic acid) helps carry out DNA's instructions and is involved in making proteins. I'm Josiah."]),
    (["what is a gene"], ["A gene is a segment of DNA that carries instructions for a trait or function. I'm Josiah."]),
    (["what is a chromosome"], ["Chromosomes are structures made of DNA and protein. They carry genes. Humans have 23 pairs. I'm Josiah."]),
    (["what is a virus"], ["A virus is a tiny infectious agent that needs a host cell to reproduce. Antibiotics don't work on viruses. I'm Josiah."]),
    (["what is bacteria"], ["Bacteria are single-celled organisms. Some help us; some cause disease. I'm Josiah."]),
    (["what is a vaccine"], ["A vaccine trains your immune system to recognise and fight a pathogen without causing the full disease. I'm Josiah."]),
    (["what is an antibiotic"], ["Antibiotics are drugs that kill or stop the growth of bacteria. They don't work against viruses. I'm Josiah."]),
    (["what is photosynthesis"], ["Photosynthesis is how plants use sunlight, water, and CO2 to make sugar and release oxygen. I'm Josiah."]),
    (["what is climate change", "global warming"], ["Climate change is long-term change in temperatures and weather, largely driven by human activity and greenhouse gases. I'm Josiah."]),
    (["what is the greenhouse effect"], ["The greenhouse effect is when gases in the atmosphere trap heat from the Sun, warming the planet. Too much intensifies climate change. I'm Josiah."]),
    (["what is renewable energy"], ["Renewable energy comes from sources that don't run out—solar, wind, water, geothermal. I'm Josiah."]),
    (["what is fossil fuel"], ["Fossil fuels (coal, oil, natural gas) come from ancient organic matter. Burning them releases CO2. I'm Josiah."]),
    (["what is electricity"], ["Electricity is the flow of electric charge (usually electrons). It powers our devices. I'm Josiah."]),
    (["what is a magnet"], ["A magnet has a magnetic field and north/south poles. Like poles repel; opposite poles attract. I'm Josiah."]),
    (["what is sound"], ["Sound is vibrations travelling through a medium (air, water). We hear when vibrations reach our ears. I'm Josiah."]),
    (["what is light"], ["Light is a form of energy that travels in waves. It can behave like a wave and like a particle (photon). I'm Josiah."]),
    (["what is a black hole"], ["A black hole is a region where gravity is so strong that nothing, not even light, can escape. I'm Josiah."]),
    (["what is the big bang"], ["The Big Bang is the theory that the universe began as an extremely hot, dense point about 13.8 billion years ago and has been expanding since. I'm Josiah."]),
    (["what is a galaxy"], ["A galaxy is a huge system of stars, gas, and dust held together by gravity. We live in the Milky Way. I'm Josiah."]),
    (["what is a light year"], ["A light year is the distance light travels in one year—about 9.5 trillion km. It's a unit of distance. I'm Josiah."]),
    (["what is an atom"], ["An atom is the smallest unit of an element. It has a nucleus (protons, neutrons) and electrons. I'm Josiah."]),
    (["what is a molecule"], ["A molecule is two or more atoms bonded together. Water (H2O) is a molecule. I'm Josiah."]),
    (["what is gravity"], ["Gravity is the force that pulls objects with mass toward each other. Earth's gravity keeps us on the ground. I'm Josiah."]),
    (["what is force"], ["In physics, force is a push or pull. Examples: gravity, friction, magnetism. I'm Josiah."]),
    (["what is energy"], ["Energy is the ability to do work. It can be kinetic (motion), potential (stored), thermal, chemical, etc. I'm Josiah."]),
    (["what is evolution"], ["Evolution is change in species over time through natural selection. Traits that help survival get passed on. I'm Josiah."]),
    (["what is natural selection"], ["Natural selection is when organisms better suited to their environment are more likely to survive and reproduce. I'm Josiah."]),
    (["what is the water cycle"], ["The water cycle: water evaporates, forms clouds, and falls as rain or snow, then flows and evaporates again. I'm Josiah."]),
    (["what is the atmosphere"], ["The atmosphere is the layer of gases around Earth—mostly nitrogen and oxygen. It protects us and gives weather. I'm Josiah."]),
    (["what is the ozone layer"], ["The ozone layer is a region in the stratosphere that absorbs harmful UV radiation. I'm Josiah."]),
    (["what is recycling"], ["Recycling turns used materials into new products to save resources and reduce waste. I'm Josiah."]),
    (["what is pollution"], ["Pollution is harmful substances in the environment—in air, water, or soil. I'm Josiah."]),
    (["what is an ecosystem"], ["An ecosystem is a community of living things and their physical environment, all interacting. I'm Josiah."]),
    (["what is a food chain"], ["A food chain shows who eats whom—energy flows from plants to herbivores to carnivores. I'm Josiah."]),
    (["what is a habitat"], ["A habitat is the natural environment where an organism lives. I'm Josiah."]),
    (["what is extinction"], ["Extinction is when a species has no living members. Dinosaurs are extinct. I'm Josiah."]),
    (["what is endangered"], ["Endangered means a species is at risk of extinction. Conservation efforts try to protect them. I'm Josiah."]),
    (["what is a mammal"], ["Mammals have fur or hair and feed milk to their young. Humans, dogs, and whales are mammals. I'm Josiah."]),
    (["what is a reptile"], ["Reptiles are cold-blooded animals with scales—snakes, lizards, turtles, crocodiles. I'm Josiah."]),
    (["what is an amphibian"], ["Amphibians live in water and on land. Frogs and salamanders are amphibians. I'm Josiah."]),
    (["what is an insect"], ["Insects have six legs and often wings. They're the largest group of animals. I'm Josiah."]),
    (["what is a bird"], ["Birds have feathers, lay eggs, and most can fly. They're warm-blooded. I'm Josiah."]),
    (["what is a fish"], ["Fish live in water, have gills, and usually have fins and scales. I'm Josiah."]),
    (["what is a marsupial"], ["Marsupials carry their young in a pouch. Kangaroos and opossums are marsupials. I'm Josiah."]),
    (["what is hibernation"], ["Hibernation is a deep sleep in winter to save energy. Bears and some rodents hibernate. I'm Josiah."]),
    (["what is migration"], ["Migration is when animals move long distances seasonally, e.g. birds flying south for winter. I'm Josiah."]),
    (["what is camouflage"], ["Camouflage is when an animal blends in with its surroundings to hide from predators or prey. I'm Josiah."]),
    (["what is the heart", "human heart"], ["The heart is a muscle that pumps blood around the body. It has four chambers. I'm Josiah."]),
    (["what is the brain", "human brain"], ["The brain is the body's control centre. It has billions of neurons and controls thought, movement, and feeling. I'm Josiah."]),
    (["what is blood"], ["Blood carries oxygen, nutrients, and waste. It contains red cells, white cells, platelets, and plasma. I'm Josiah."]),
    (["what is the liver"], ["The liver filters blood, helps with digestion, and stores energy. It's a vital organ. I'm Josiah."]),
    (["what are kidneys"], ["Kidneys filter waste from the blood and make urine. We have two. I'm Josiah."]),
    (["what is the stomach"], ["The stomach holds and churns food, adding acid and enzymes to start digestion. I'm Josiah."]),
    (["what is the immune system"], ["The immune system fights germs and disease. It includes white blood cells and antibodies. I'm Josiah."]),
    (["what is stress"], ["Stress is the body's response to pressure or threat. Some stress is normal; too much can affect health. I'm Josiah."]),
    (["what is anxiety"], ["Anxiety is worry or fear that can be normal or excessive. Exercise, sleep, and support can help. I'm Josiah."]),
    (["what is a calorie"], ["A calorie is a unit of energy in food. The body uses calories for fuel. I'm Josiah."]),
    (["what is protein"], ["Protein is a nutrient that builds and repairs tissues. It's in meat, beans, eggs, and dairy. I'm Josiah."]),
    (["what is vitamin c"], ["Vitamin C helps the immune system and skin. It's in citrus fruits and many vegetables. I'm Josiah."]),
    (["what is calcium"], ["Calcium is a mineral that builds strong bones and teeth. It's in dairy and leafy greens. I'm Josiah."]),
    (["what is fiber", "what is fibre"], ["Fibre is plant matter we can't fully digest. It helps digestion and is in whole grains, fruits, and vegetables. I'm Josiah."]),
    (["what is the internet"], ["The internet is a global network of connected computers that share information. I'm Josiah."]),
    (["what is wifi", "what is wi-fi"], ["Wi‑Fi is wireless technology that lets devices connect to the internet without cables. I'm Josiah."]),
    (["what is ai", "what is artificial intelligence"], ["AI is when machines do tasks that usually need human intelligence—learning, reasoning, understanding language. I'm Josiah."]),
    (["what is a robot"], ["A robot is a machine that can carry out tasks automatically, often programmed by a computer. I'm Josiah."]),
    (["what is coding", "what is programming"], ["Coding is writing instructions for computers in a programming language. It powers apps and websites. I'm Josiah."]),
    (["what is python"], ["Python is a popular programming language used for web apps, data science, and automation. I'm Josiah."]),
    (["what is the capital of france"], ["The capital of France is Paris. I'm Josiah."]),
    (["what is the capital of japan"], ["The capital of Japan is Tokyo. I'm Josiah."]),
    (["what is the capital of australia"], ["The capital of Australia is Canberra. I'm Josiah."]),
    (["what is the capital of canada"], ["The capital of Canada is Ottawa. I'm Josiah."]),
    (["what is the capital of the usa"], ["The capital of the United States is Washington, D.C. I'm Josiah."]),
    (["what is the capital of the uk"], ["The capital of the United Kingdom is London. I'm Josiah."]),
]
